id: 31d7008659cf41919edba6c0754e6d59
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_283-The_Sutra_of_the_Three_Bodies-v1
  language: en
  author: ''
  volume: {}
